name = "hello_ada"
description = ""
version = "0.1.0-dev"

authors = ["Syed Azeez"]
maintainers = ["Syed Azeez <syedazeez337@gmail.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["hello_ada"]
